"""empty message

Revision ID: 66d7b4f014bd
Revises: 
Create Date: 2022-08-20 18:03:49.911663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66d7b4f014bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_base',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=20), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('faceAuth', sa.Boolean(), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('last_login_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('job_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user_base.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('behavior',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lower_login_time', sa.DateTime(), nullable=False),
    sa.Column('upper_login_time', sa.DateTime(), nullable=False),
    sa.Column('lower_logout_time', sa.DateTime(), nullable=False),
    sa.Column('upper_logout_time', sa.DateTime(), nullable=False),
    sa.Column('lower_upload_count', sa.Integer(), nullable=False),
    sa.Column('upper_upload_count', sa.Integer(), nullable=False),
    sa.Column('lower_download_count', sa.Integer(), nullable=False),
    sa.Column('upper_download_count', sa.Integer(), nullable=False),
    sa.Column('lower_delete_count', sa.Integer(), nullable=False),
    sa.Column('upper_delete_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_base.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('actionType', sa.String(length=80), nullable=False),
    sa.Column('done_at', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_base.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('upload',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=80), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_base.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user_base.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('upload')
    op.drop_table('log')
    op.drop_table('behavior')
    op.drop_table('admin')
    op.drop_table('user_base')
    # ### end Alembic commands ###
